### ISSUE TITLE
Integrate KEGG using new KEGGtranslator

### ISSUE THREAD

**Issue by GoogleCodeExporter** [PathwayCommons/cpath2#147]
```
Data source: KEGG

This is experimental. 
Despite having (the team created) 
[http://www.cogsys.cs.uni-tuebingen.de/software/KEGGtranslator this new tool], 
there are still licensing concerns... 
We can try this (convert, validate, merge) internally first. If success, we 
should probably ask/encourage KEGG team to allow free open (or academic) access 
only to the resulting BioPAX L3 file.


```

Original issue reported on code.google.com by `rod...@gmail.com` on 21 Jun 2012 at 6:19

**Comment by IgorRodchenkov** [comment]
Finally, we used (old and free) KEGG *.hsa pathways converted to BioPAX L3 by the BioModels / Path2Models  team (Andreas Draeger, Clemens Wrzodek) using KEGGTranslator (which uses KEGG web api to retrieve annotations about Entrez IDs, UniProt IDs, Gene descriptions, etc.)

http://www.cogsys.cs.uni-tuebingen.de/mitarb/draeger/BioPAX.zip (~142,000 files; it still lacks 17,000 files that could not be translated; but we'll only import into PC2 db human, *.hsa converted files for now).

This KEGG -> BioPAX conversion was mainly designed and implemented by Finja and me and was not a topic of the Path2Models project. Andreas was and is still a main developer of KEGGTranslator and kindly took over the support for the whole application. The knowledge for creating the conversion also came from Igor in some email conversations we had some years ago. The conversion itself and all people involved in it are mentioned in http://www.biomedcentral.com/1752-0509/7/15 ...
The whole code has been designed and tailored specifically for an appropriate transformation of KEGG Pathways to BioPAX, respecting the particularities of that Modeling Language.

Here is now also the script that is used to convert from KEGG to BioPAX
L3. It takes two inputs $1 and $2, which are the source directory with
KEGG files and the output directory where to place the result:

```bash
#!/bin/sh
#Get rid of the GC-conf error
eval `dbus-launch --sh-syntax`

java -Xms1G -Xmx8G -jar ./KEGGtranslatorV2.3.0.jar \
-i$1 -o$2 \
-fBioPAX_level3 \
--cache-size 1000000 \
--clear-fail-cacheTRUE \
--remove-orphans=true \
--gene-names=INTELLIGENT \
--remove-white-gene-nodes=true \
--autocomplete-reactions=true \
--check-atom-balance=true \
--check-for-updates=false \
--gui=false \
--log-level=FINE
exit 0
```

So, we won't convert KEGG files ourselves; we will use Path2Models' and do additional cleaning and normalizing. See also: a related issue #205
