### ISSUE TITLE
Integrate PharmGKB (BioPAX)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [PathwayCommons/cpath2#170]
```
Data source: PharmGBKB
Date downloaded: December 2012

Data source issue:

EntityReference does not have any xrefs
Syntax error. This is usually caused by XML/RDF/OWL syntax problems found while 
reading the input BioPAX document

Is the data source aware of the issue? Not yet. 

Example file with errors is attached, but other files have similar errors. 


```

Original issue reported on code.google.com by `can...@gmail.com` on 12 Nov 2013 at 3:25

Attachments:
- [PA165291507_Fluoropyrimidine_Pathway_Pharmacodynamics.owl_validate.html](https://storage.googleapis.com/google-code-attachments/pathway-commons/issue-170/comment-0/PA165291507_Fluoropyrimidine_Pathway_Pharmacodynamics.owl_validate.html)
- [PA165291507_Fluoropyrimidine_Pathway_Pharmacodynamics.owl](https://storage.googleapis.com/google-code-attachments/pathway-commons/issue-170/comment-0/PA165291507_Fluoropyrimidine_Pathway_Pharmacodynamics.owl)

**Comment by IgorRodchenkov** [comment]
It's still not ready. Won't do.
