### ISSUE TITLE
Downloads Page Slow to Load

### ISSUE THREAD

**Issue by cannin** [PathwayCommons/cpath2#206]
Downloads page is slow to load: http://www.pathwaycommons.org/pc2/downloads

**Comment by emekdemir** [comment]
We probably should not calculate/report statistics..

**Comment by IgorRodchenkov** [comment]
This issue turned out to be related to issue #209 (which was the main reason for the slow-down, among others)

**Comment by IgorRodchenkov** [comment]
Re-deployed on the test and production servers 
(The "/datasources" and "/provides" pages do not have those badges with real-time counts anymore, but links to the corresponding stats/ips instead).
