### ISSUE TITLE
A neigborhood query throws exception

### ISSUE THREAD

**Issue by IgorRodchenkov** [PathwayCommons/cpath2#219]
`http://www.pathwaycommons.org/pc2/graph?source=P01112&kind=neighborhood&limit=2`

Internal Server Error; Internal Server Error - org.biopax.paxtools.util.IllegalBioPAXArgumentException: I already have an object with the same ID: `http://purl.org/pc2/7/RelationshipXref_protein+genbank+identifier_193786913`. Try removing it first; [org.biopax.paxtools.impl.ModelImpl.add(ModelImpl.java:154), org.biopax.paxtools.impl.ModelImpl.addNew(ModelImpl.java:119), org.biopax.paxtools.controller.Cloner.clone(Cloner.java:49), cpath.service.CPathServiceImpl.getNeighborhood(CPathServiceImpl.java:277), cpath.webservice.BiopaxModelController.graphQuery(BiopaxModelController.java:242), sun.reflect.GeneratedMethodAccessor338.invoke(Unknown Source), sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.lang.reflect.Method.invoke(Method.java:606), org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:215), org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132
...
etc.
What happens is - Cloner.clone([Cloner.java:49](https://github.com/PathwayCommons/cpath2/blob/master/cpath-impl/src/main/java/cpath/service/CPathServiceImpl.java#L277)) fails due to the 'elements' set (second parameter) for some unknown reason contains more than one biopax objects with rdf:ID="RelationshipXref_protein+genbank+identifier_193786913".

It's weird to see such exception... that's probably caused by some server failure, intermediate state, previous OutOfMemory exception...

**Comment by ozgunbabur** [comment]
I tried the same query using paxtools on the largest v7 owl, and it worked without errors. We'll need to track this bug in cpath2.

**Comment by IgorRodchenkov** [comment]
Ok, thanks Ozgun


Igor

**Comment by IgorRodchenkov** [comment]
I think, we simply should never allow users execute PC2 neighborhood graph
queries with limit>1 (at least never return the result as BioPAX)...

Does it make sense to return >1Gb RDF/XML data from a simple query like:
/graph?source=P01112&kind=neighborhood&limit=2 that also would take several
minutes to complete?

Ozgun successfully tried the same data/query outside PC2 (barring
blacklist.txt) and got 1.3Gb output BioPAX file.
So, while it works with a file output stream (handler.convertToOWL(ex, new
FileOutputStream("temp.owl"));),
it does not - in PC2 that writes the result biopax model to a byte array in
the web app/servlet context to return the OWL data to the web user...

Alternatively, we have to re-design and re-factor how PC2 returns results;
i.e., use tmp files, queues, push notifications, etc... Argh....

IR.

**Comment by ozgunbabur** [comment]
If we will limit the limit, then it may make sense to do it when the
direction is "undirected" (currently this is the default for neighborhood).
If we make the query directed by setting the direction to "bothstream", the
result size reduces to 69.9MB, almost half the size.

While 2 neighborhood of HRAS is too big, it is not the case for every
protein. If someone is working on a less known protein, and if its
neighborhood is so small, she will instantly query for a bigger
neighborhood. Not being able to do that may be annoying.

**Comment by IgorRodchenkov** [comment]
I could both a) limit the 'limit' when the 'direction' is "undirected"
(default) and b) slightly refactor inside cpath2 to use and pass internally
temporary files instead of byte[]...
By the way, ~70Mb is not half the size of 1.3Gb ;)

**Comment by ozgunbabur** [comment]
Oh. yes it is not half, it is 19 time smaller :)

**Comment by IgorRodchenkov** [comment]
This is now fixed in the sources and test PC2 server 
(though, I did not limit the 'limit' parameter value to 1 when the 'direction' is "undirected",
but instead made use of temporary files internally to carry query result data inside cpath2).
