### ISSUE TITLE
Incorrect Pubmed IDs in Extended SIF

### ISSUE THREAD

**Issue by cannin** [PathwayCommons/cpath2#239]
I just noticed these weird entries for Pubmed IDs. I see it for IntAct interactions not sure if it happens elsewhere. Pubmed IDs should only have numbers.

grep "unassigned1272" PathwayCommons.8.All.EXTENDED_BINARY_SIF.hgnc.txt | head

AAAS interacts-with ABHD12 IntAct unassigned1272
http://purl.org/pc2/8/MolecularInteraction_1452625931256

These should be removed if there is no way of resolve them.

**Comment by IgorRodchenkov** [comment]
Done ([test search](http://beta.pathwaycommons.org/pc2/search?q=unassigned&type=PublicationXref) does not return any hits)
