### ISSUE TITLE
Tabs on pathway page are squished

### ISSUE THREAD

**Issue by GoogleCodeExporter** [PathwayCommons/cpath2#24]
```
What steps will reproduce the problem?
1.  Go to a pathway page, e.g.
http://awabi.cbio.mskcc.org/pc-demo/record2.do?id=604467 (FOXA1
transcription factor network)

What is the expected output? What do you see instead?

1.  The tabs are all squished up at the top.  See attached screenshot.


```

Original issue reported on code.google.com by `cer...@gmail.com` on 12 Oct 2009 at 3:42

Attachments:
- [screenshot.png](https://storage.googleapis.com/google-code-attachments/pathway-commons/issue-24/comment-0/screenshot.png)

**Comment by IgorRodchenkov** [comment]
This issue was moved to PathwayCommons/cpath1#27
