### ISSUE TITLE
No bootstrap styling in views on first load

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/cpath2#242]
When attempting to load web pages (first time and after clearing cache) there is no accompanying  styling (e.g. beta.pathwaycommons.org/pc2/formats, beta.pathwaycommons.org/pc2/downloads). This coincides with the the absence of 'bootstrap.min.css' loaded in the browser. Subsequent refresh does load the bootstrap.min.css however.

Note: Call to boostrap.min.css appears alongside other style files that are successfully loaded as part of the jsp head partial: cpath2/cpath-web-service/src/main/webapp/WEB-INF/views/head.jsp.  
```
jsp:include page="head.jsp"
```

**Comment by IgorRodchenkov** [comment]
@jvwong thanks for looking into and reporting this weird bug (it does not look wrong in the sources).
This issue here merely duplicates #240 but is more specific.

**Comment by IgorRodchenkov** [comment]
Ah, typo bug in the href=...
