### ISSUE TITLE
Pathway Missing to from pathways.txt

### ISSUE THREAD

**Issue by cannin** [PathwayCommons/cpath2#258]
This exists in Pathway Commons 8: 
http://www.pathwaycommons.org/pc2/get?uri=http://identifiers.org/reactome/R-HSA-1640170

This does not exist in the pathways.txt from http://www.pathwaycommons.org/archives/PC2/current/pathways.txt.gz:
grep "http://identifiers.org/reactome/R-HSA-1640170" pathways.txt

http://identifiers.org/reactome/R-HSA-1640170 is Reactome Cell Cycle

**Comment by IgorRodchenkov** [comment]
Confirmed. It's a [root/top pathway](http://pathwaycommons.org/pc2/top_pathways?datasource=reactome&q=name:%22Cell%20Cycle%22).

Now looking...

**Comment by IgorRodchenkov** [comment]
Sadly, indeed, there seems to be a bug in how the pathways.txt (pathways hierarchy) was generated.

Here is another example of missing pathway [R-HSA-73894](http://pathwaycommons.org/pc2/top_pathways?datasource=reactome) from Reactome: "http://identifiers.org/reactome/R-HSA-73894" ("DNA Repair", large pathway)

However, other "top pathways" (from Reactome) are present there in the pathways.txt, e.g. "http://identifiers.org/reactome/R-HSA-76044" (a smaller one), "http://identifiers.org/reactome/R-HSA-382551" (as large as missing R-HSA-73894 one) or "http://identifiers.org/reactome/R-HSA-74160" (much larger pathway)...

I am still looking... (looks, pathway size or being root/top does not help me to know why some were excluded from the file...)

**Comment by IgorRodchenkov** [comment]
Fixed Paxtools bug BioPAX/Paxtools#20, generated a new pathways.txt file and replaced it and paxtools.jar in http://www.pathwaycommons.org/archives/PC2/current/
