### ISSUE TITLE
Integrate I2D (human) data

### ISSUE THREAD

**Issue by IgorRodchenkov** [PathwayCommons/cpath2#279]
#  Interologous Interaction Database (I2D)

- availability: academic (non-profit);
- format: PSI-MI 2.5; version: 2.9; 2015-07-10; human;
- home page: http://ophid.utoronto.ca/ophidv2.204/
- download URL: http://ophid.utoronto.ca/ophidv2.204/downloads.jsp

**Comment by IgorRodchenkov** [comment]
So, we'll  simply run the Paxtools' psimi-converter to auto-convert these data to BioPAX Level3 (see also cli command: toLevel3), to integrate into PC10 - the same way we process IntAct, BioGRID, etc..

Nothing else to do.

**Comment by IgorRodchenkov** [comment]
_**News:**_
@gbader, @jvwong  - [IID](http://iid.ophid.utoronto.ca/SearchPPIs/protein/) is a major replacement of the I2D; see PMID:[26516188](https://www.ncbi.nlm.nih.gov/pubmed/26516188)

**Comment by gbader** [comment]
Should we forget about i2d?

**Comment by IgorRodchenkov** [comment]
Does  it make sense to build a from IID (TSV format) to BioPAX converter
from scratch?
I could start this (next IID PSIMITAB version will likely arrive in several
weeks...)

Example data:
uniprot1^Iuniprot2^Isymbol1^Isymbol2^Imethods^Ipmids^Idbs^Ievidence
type^Iadipose tissue^Iadrenal gland^Iamygdala^Ibone^Ibone
marrow^Ibrain^Idorsal root ganglia^Ieye^Iheart^Ihindgut^
Ihypothalamus^Ikidney^IQ96DB2^IQ96EY1^IHDAC11^IDNAJA3^Iaffinity
chromatography technology,anti tag coimmunoprecipitation^
I23752268^Ibiogrid,intact^Iexp^IG^IG^IG^IG^IG^IG^IG^I-^
IG^IG^IG^IG^IG^IG^IG^IG^IG^IG^IG^IG^IG^IG^IG^IG^IG^I
...

Otherwise, let's postpone adding IID/I2D untill PC10 (December?)

IR.

**Comment by IgorRodchenkov** [comment]
I2D is also part of IntAct.
