### ISSUE TITLE
Integrate CSNDB (challenge)

### ISSUE THREAD

**Issue by IgorRodchenkov** [PathwayCommons/cpath2#283]
A challenging task - requires understanding of the db (dump file) format, mapping to BioPAX L3 and writing a converter code (e.g., in Java or Python)...

https://www.ncbi.nlm.nih.gov/pubmed/10072089

**Comment by IgorRodchenkov** [comment]
Paper [here](http://online.liebertpub.com/doi/pdfplus/10.1089/cmb.1998.5.747).

Found only (2001) data files [via webarchive.org](https://web.archive.org/web/20040622075900/http://geo.nihs.go.jp:80/csndb/);
[downloaded from here](https://web.archive.org/web/20010727144346/http://geo.nihs.go.jp:80/csndb/acedata/)

[Licence](https://web.archive.org/web/20040227192125/http://geo.nihs.go.jp:80/csndb/agreement.html).

> LICENCE AGREEMENT
> 
> The intellectual property right of CSNDB belongs to National Institute of Health Sciences (NIHS). Use of the CSNDB database is free for academic and commercial users. Takako Takai-Igarashi of NIHS is responsible for the scientific content of CSNDB.
> 
> Integration of all of CSNDB into another database will require explicit permission from NIHS. Such permission will only be granted if there is a valid scientific or technical reason to encapsulate the entire content of CSNDB into a new resource. In that case, you will become a redistributor of CSNDB and the rules for the redistributor will be applicable.
> 
> Integration of any part of CSNDB into any commercial product is rigidly prohibited in any case.
> 
> If you intend to publish a book which contains the printout of a significant number of entries from the database, you need to ask explicitly for permission.
> 
> If you are redistributing CSNDB you need to explicitly ask permission to do so by registering your service with NIHS. In that case, you should agree with the following:
> 
> In the case of a WWW or FTP server, you are asked to make available to NIHS that part of your log files that specifically deals with access to CSNDB.
> You must timely update the copy of CSNDB.
> You should not redistribute CSNDB in a format other than original one.
> You should make available to some information about CSNDB; bibliographies, user’s guide and the database scheme.
> Publication of results obtained with the aid of CSNDB resources should cite:
> 
> Takako Takai-Igarashi and Tsuguchika Kaminuma : A Pathway Finding System for the Cell Signaling Networks Database, In Silico Biology, 1, pp.129-146, (1999).
> 
> If you have questions, please send an email to the following address:
> 
> Dr. Takako Takai-Igarashi : taka@nihs.go.jp
> 
> Last Update July. 7, 2000
>

**Comment by gbader** [comment]
great sleuthing!  We can try to contact that person.  My guess is that they would have no trouble making this resource available for free now.  However, we should check that we can actually process and use it first.
