### ISSUE TITLE
Graph Function Documentation Mentions BINARY_SIF That No Longer Exists

### ISSUE THREAD

**Issue by cannin** [PathwayCommons/cpath2#305]
Mention of BINARY_SIF in the current documentation is probably an error. 

"the result BioPAX model (e.g., BINARY_SIF output ..."

But given that we provide the previous versions downloads, should the previous documentation be kept somewhere? Version 8 did contain output labeled BINARY_SIF: 

http://www.pathwaycommons.org/archives/PC2/v8/

**Comment by IgorRodchenkov** [comment]
Looks, you're correct.

Although http://www.pathwaycommons.org/pc2/formats mentions moth old and new formtat names, we'd better make it more clear on the PC web service description page too.

**Comment by IgorRodchenkov** [comment]
Also - updated the format descriptions [there](http://www.pathwaycommons.org/pc2/#output_formats).
