### ISSUE TITLE
v11/ beta: Unable to GET SBGN format  

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/cpath2#309]
I was unable to perform a web service call to GET an object URI identified via SEARCH in SBGN format. The expectation is that SBGN format is returned. 

To reproduce:

- Search: `q=pcna` for pathways (http://beta.pathwaycommons.org/pc2/search?q=pcna&type=Pathway)
- GET: `uri=http://identifiers.org/reactome/R-HSA-110314` (http://beta.pathwaycommons.org/pc2/get?format=sbgn&uri=http://identifiers.org/reactome/R-HSA-110314)

```
{
  "timestamp": 1548698215475,
  "status": 500,
  "error": "Internal Server Error",
  "message": "500; Internal Server Error - java.lang.NullPointerException;
  ...,
  "path": "/pc2/get"
}
```

**Comment by IgorRodchenkov** [comment]
I’ll look into this soon; thanks Jeff.

IR
