### ISSUE TITLE
Questions about deployment

### ISSUE THREAD

**Issue by metincansiper** [PathwayCommons/cpath2#311]
Hi there,
I need to deploy this service to a server. Therefore, I have started to try it on my computer first. The best for me would be deploying it with a single command in any environment. Therefore, I tried to do it through the docker file that is available inside the project. However, I realized that there could be some pre-work to do before using that docker file. Am I right?

Then, I decided to start by following the steps in readme (without using the docker file). I have updated the ``metadata.json`` as the following:

```
{
  "description": "Pathway Commons data sources (metadata)",
  "version": 11,
  "datasources": [
    {
      "dataUrl": "ftp:\/\/ftp.ebi.ac.uk\/pub\/databases\/chebi\/ontology\/chebi.obo",
      "identifier": "chebi",
      "homepageUrl": "https:\/\/www.ebi.ac.uk\/chebi\/",
      "name": [
        "ChEBI"
      ],
      "converterClass": "cpath.converter.ChebiOboConverter",
      "description": "ChEBI Ontology v171, 02-Jan-2019",
      "iconUrl": "https:\/\/pathwaycommons.github.io\/cpath2\/logos\/chebi.png",
      "availability": "free",
      "type": "WAREHOUSE",
      "pubmedId": "23180789"
    },
    {
      "dataUrl": "ftp:\/\/ftp.uniprot.org\/pub\/databases\/uniprot\/current_release\/knowledgebase\/taxonomic_divisions\/uniprot_sprot_human.dat.gz",
      "identifier": "uniprot_human",
      "homepageUrl": "https:\/\/www.uniprot.org",
      "name": [
        "UniProt",
        "SwissProt",
        "UniProtKB"
      ],
      "converterClass": "cpath.converter.UniprotConverter",
      "description": "UniProtKB\/Swiss-Prot (human), 17-Jan-2019",
      "iconUrl": "https:\/\/pathwaycommons.github.io\/cpath2\/logos\/uniprot.png",
      "availability": "free",
      "type": "WAREHOUSE",
      "pubmedId": "24253303"
    },
    {
      "dataUrl": "http:\/\/www.reactome.org\/download\/current\/biopax.zip",
      "identifier": "reactome_human",
      "homepageUrl": "https:\/\/www.reactome.org",
      "cleanerClass": "cpath.cleaner.ReactomeCleaner",
      "name": [
        "Reactome"
      ],
      "description": "Reactome v67 (only 'Homo_sapiens.owl') 13-Dec-2018",
      "iconUrl": "https:\/\/pathwaycommons.github.io\/cpath2\/logos\/reactome.png",
      "availability": "free",
      "type": "BIOPAX",
      "pubmedId": "29145629"
    }
  ]
}
```

I have downloaded, extracted/renamed/repacked the related files as mentioned in readme in a way that they are compatible with ``description`` field. However, for biopax I have downloaded the version 1 (I suppose so because it was named as biopax.zip) because only version 1 and version 2 is available, version 3 is missing (https://reactome.org/download/current/). I did not download the ``wholeSourceMapping`` (ftp://ftp.ebi.ac.uk/pub/databases/chembl/UniChem/data/wholeSourceMapping/src_id1/) because I suppose it is already being downloaded where it is used (e.g. https://github.com/PathwayCommons/cpath2/blob/master/work/prep_idmaps.sh#L14).

When I try to build the project in this way I see the following error in ``cpath2.log``:

```
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:816)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:797)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:324)
	at cpath.Application.main(Application.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:58)
Caused by: java.lang.IllegalArgumentException: The blacklist is empty
	at org.springframework.util.Assert.notEmpty(Assert.java:464)
	at cpath.service.CPathServiceImpl.loadBlacklist(CPathServiceImpl.java:644)
	at cpath.service.CPathServiceImpl.init(CPathServiceImpl.java:105)
	at cpath.service.CPathServiceImpl.index(CPathServiceImpl.java:724)
	at cpath.service.ConsoleApplication.index(ConsoleApplication.java:184)
	at cpath.service.ConsoleApplication.run(ConsoleApplication.java:119)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:813)
	... 11 common frames omitted
```

It tells that the error is caused by the blacklist is empty. However, the blacklist file is not something that I edited I suppose it must be downloaded by the script or pre-existing. Do you have any idea what is wrong and/or what should I do to fix it?

Also, is it possible to deploy in an easier way using the docker file? I think this project is deployed in web. If you have an automated deployment script that you can share, it could be great. The answer for my other questions would not be so important if I had such a script.

**Comment by metincansiper** [comment]
BTW when I tried to exclude ``reactome`` the build was successful. However, when I run the service any of the few queries that I tried gave empty results (I suppose it may already be something expected for that case).

**Comment by IgorRodchenkov** [comment]
We only maintained this application as part of Pathway Commons project and don’t officially nor normally provide any special support for others to build and deploy this application or data somewhere else. You’re free to use the code and figure out how to build and run it.

Igor R.

**Comment by metincansiper** [comment]
I am working with @emekdemir what we are trying to figure it out for PC.

**Comment by IgorRodchenkov** [comment]
It is doable, please try to figure out from readme and code. A cPath2 web service can be run with a single java command, but it does take time and effort to properly prepare all the data sources, in that work directory, validate, build the models, Lucene index, and build output data files. 

**I am closing this ticket, because it's kind of support request with humble opinion or review and not a user story or bug report to work with.** Otherwise this discussion never ends. For cPath2 build/code improvements we don't have s/w engineers anymore (researchers or students doing own/side projects and papers are not counted).
