### ISSUE TITLE
Datasource metadata for Biofactoid

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/cpath2#313]
Add Biofactoid-related information and populate the associated datasource metadata. In particular:

- `iconUrl`: Need logo, something like [the one in biofactoid](https://github.com/PathwayCommons/factoid/blob/unstable/src/styles/image/logo.png)
- `pubmedid`: 34860157

**Comment by metincansiper** [comment]
@jvwong other logos are stored in url's under pathwaycommons.github.io/cpath2/logos (e.g. https://pathwaycommons.github.io/cpath2/logos/reactome.png). Should I store this image there as well? If so how can I put this image there? I could not see any github pages for pathwaycommons.

**Comment by jvwong** [comment]
GitHub pages are served from the data in the [`gh-pages`](https://github.com/PathwayCommons/cpath2/tree/gh-pages/) branch. So logos probably go:  https://github.com/PathwayCommons/cpath2/tree/gh-pages/logos

**Comment by metincansiper** [comment]
Thank you @jvwong I added a resized version of image under logos and updated metadata.json file as discussed here.
