### ISSUE TITLE
H2 datasource URL args

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/cpath2#316]
> On building I noticed an error (org.h2.jdbc.JdbcSQLNonTransientConnectionException: Unsupported connection setting "MVCC"). 
>  if I edit application.properties so that '’spring.datasource.url” does NOT include ‘MV_STORE=FALSE;MVCC=FALSE’ the build is fine and the server runs OK.

Links:
- https://github.com/h2database/h2database/releases/tag/version-1.4.200
- https://github.com/h2database/h2database/issues/2413#issuecomment-577956545

**Comment by IgorRodchenkov** [comment]
fixed
