### ISSUE TITLE
Linking from NCBI (Entrez) Gene, UniProt to PC

### ISSUE THREAD

**Issue by GoogleCodeExporter** [PathwayCommons/cpath2#36]
```
We need to link Entrez Gene to pathwaycommons.org

This requires building XML files to submit to Entrez Gene.

We probably want to automatically generate these files with every PC build (and 
include the feature with cpath2 as well, so code should be reuable between 
cpath1 and 2)
```

Original issue reported on code.google.com by `gary.bad...@gmail.com` on 18 Nov 2010 at 3:16

**Comment by IgorRodchenkov** [comment]
And - linking from UniProt to PathwayCommons (e.g., link by primary UniProt accession to the PCViz view for that protein's neighborhood)

**Comment by IgorRodchenkov** [comment]
@gbader @jvwong @cannin 
We can now link a gene ID/symbol to the Pathways [search app](http://www.pathwaycommons.org/pathways/).

**Comment by IgorRodchenkov** [comment]
A new issue #294 continues this older one; so closing...
