### ISSUE TITLE
Reactome generic issue

### ISSUE THREAD

**Issue by GoogleCodeExporter** [PathwayCommons/cpath2#37]
```
Data source: Reactome
Date downloaded: All
Version, if available: at least up to Nov.2010
File name downloaded:
File location:

Data source issue:
Reactome encodes generics as entity sets. This causes a problem when converting 
to BioPAX, as generic features can not be properly converted, thus Reactome is 
forced to use the bad practice shortcut of converting the entity set to a 
physical entity set of references which avoids use of the official generic 
system in BioPAX. Reactome needs an analysis of this issue along with some 
examples to consider it.

Is the data source aware of the issue?
Yes - contact is Guanming Wu and Peter D'Eustachio
```

Original issue reported on code.google.com by `gary.bad...@gmail.com` on 18 Nov 2010 at 3:20

**Comment by IgorRodchenkov** [comment]
Well, despite BioPAX does not recommend using `memberPhysicalEntity` property at all, Reactome (and perhaps others) have been using this for years...

Why cannot we simply apply the following "fix" for each such "generic" physical entity (at least - for complexes, to begin with) in a BioPAX model:

_If P.memberEntityReference contains `P1,.. Pn` physical entities, and `P` participates in an Interaction (or is component of a Complex) `R`, then we'd simply get rid of `P` by cloning `R` - making `R1,..Rn` for each alternative member to be the participant `P1,..Pn`, respectively._

I could write the code and run it for all the data in PC, probably, after the merge stage (can be done by next PC10 release; then, it'd solve mapping to SBGN problem, i.e.,, dangling member physical entities).

Refs PathwayCommons/app-ui#228

@emekdemir @jvwong @ozgunbabur

**Comment by IgorRodchenkov** [comment]
The BioPAX to SBGN converter has been already improved.
Reacome is not going to address _memberPhysicalEntity_ problem in their BioPAX export; so I am closing this issue.
